In [1057]:
import pandas as pd

In [1058]:
gdp_per_capita = pd.read_csv("GDP_per_Capita.csv")
life_expectancy = pd.read_csv("Life Expectancy.csv")
male_ratio = pd.read_csv("Male Population Ratio.csv")
population = pd.read_csv("Population.csv")
old_ratio = pd.read_csv("Retirement Age Dependency Ratio.csv")
area = pd.read_csv("Total Area (sq km).csv")
urban_population_ratio = pd.read_csv("Urban Population Ratio.csv")
sdg_regions = pd.read_csv("world_regions_sdg.csv")
young_ratio = pd.read_csv("Young Age Dependency Ratio.csv")

In [1059]:
infant_mortality = pd.read_csv("Infant Mortality.csv")
infant_mortality.drop(columns="Variant",inplace=True)
infant_mortality.rename(columns={"Value":"Infant mortality per 1000 live births"},inplace=True)

In [1060]:
country_codes = pd.read_csv("country_codes.csv")
country_codes = country_codes.drop(columns= "Code")
country_codes['ISO3'] = country_codes['ISO3'].replace('ROM', 'ROU')
country_codes['ISO3'] = country_codes['ISO3'].replace('ZAR', 'COD')
country_codes['ISO3'] = country_codes['ISO3'].replace('TMP', 'TLS')
new_data = {
    'ISO3': ['MNE', 'SRB'],
    'Country': ['Montenegro', 'Serbia']
}
new_countries = pd.DataFrame(new_data)
for _, row in new_countries.iterrows():
    iso3 = row['ISO3']
    country = row['Country']
    if iso3 not in country_codes['ISO3'].values and country not in country_codes['Country'].values:
        country_codes = pd.concat([country_codes, pd.DataFrame([row])], ignore_index=True)
country_codes

                            Country ISO3
0                       Afghanistan  AFG
1                           Albania  ALB
2                           Algeria  DZA
3                    American Samoa  ASM
4                           Andorra  AND
..                              ...  ...
261  Yugoslavia, FR (Serbia/Montene  YUG
262                          Zambia  ZMB
263                        Zimbabwe  ZWE
264                      Montenegro  MNE
265                          Serbia  SRB

[266 rows x 2 columns]

In [1061]:
rawbmi = pd.read_csv("bmi_data.csv")
rawbmi = rawbmi[rawbmi["SpatialDimType"] == 'COUNTRY']
rawbmi = rawbmi[["SpatialDim","Dim1","TimeDim","NumericValue"]]
rawbmi = rawbmi.pivot_table(
    index=['TimeDim', 'SpatialDim'], 
    columns='Dim1', 
    values='NumericValue'
).reset_index()
rawbmi.rename(columns={'TimeDim': 'Year', 'SpatialDim': 'ISO3','SEX_BTSX':"BMI","SEX_FMLE":"BMI Female","SEX_MLE":"BMI Male"}, inplace=True)
rawbmi['ISO3'] = rawbmi['ISO3'].replace('SDN736', 'SDN')
rawbmi

Dim1  Year ISO3   BMI  BMI Female  BMI Male
0     1975  AFG  18.9        18.9      19.0
1     1975  AGO  18.8        18.9      18.7
2     1975  ALB  23.8        23.8      23.8
3     1975  AND  25.4        25.7      25.0
4     1975  ARE  25.3        26.8      24.7
...    ...  ...   ...         ...       ...
8017  2016  WSM  32.2        34.1      30.4
8018  2016  YEM  23.8        24.1      23.6
8019  2016  ZAF  27.3        29.3      25.0
8020  2016  ZMB  22.6        23.7      21.3
8021  2016  ZWE  23.8        25.3      22.2

[8022 rows x 5 columns]

In [1062]:
bmi = pd.merge(country_codes,rawbmi,on="ISO3",how='inner')
bmi = bmi.drop(columns="ISO3")
bmi

          Country  Year   BMI  BMI Female  BMI Male
0     Afghanistan  1975  18.9        18.9      19.0
1     Afghanistan  1976  19.0        19.0      19.1
2     Afghanistan  1977  19.2        19.1      19.2
3     Afghanistan  1978  19.3        19.3      19.3
4     Afghanistan  1979  19.4        19.4      19.4
...           ...   ...   ...         ...       ...
8017       Serbia  2012  25.9        25.4      26.4
8018       Serbia  2013  25.9        25.4      26.4
8019       Serbia  2014  26.0        25.4      26.5
8020       Serbia  2015  26.0        25.5      26.6
8021       Serbia  2016  26.1        25.5      26.6

[8022 rows x 5 columns]

In [1063]:
def changeCountryName(oldnames, new_name):
    datasets = [
        (bmi, 'Country'),
        (gdp_per_capita, 'Country'),
        (life_expectancy, 'Country'),
        (male_ratio, 'Country'),
        (old_ratio, 'Country'),
        (young_ratio, 'Country'),
        (population, 'Country'),
        (urban_population_ratio, 'Country'),
        (area, 'Country'),
        (infant_mortality, 'Country or Area'),
        (sdg_regions, 'Country/area')
    ]
    for df, column in datasets:
        if column in df.columns:
            df[column].replace(oldnames, new_name, inplace=True)

In [1064]:
changeCountryName(["Venezuela (Bolivarian Republic of)","Venezuela, RB"],"Venezuela")
changeCountryName("Viet Nam","Vietnam")
changeCountryName(["Democratic Republic of the Congo", "Democratic Republic of Congo", "Congo, Dem. Rep."], "Democratic Republic of the Congo")
changeCountryName(["Congo, Rep."], "Congo")
changeCountryName(["Bolivia (Plurinational State of)"], "Bolivia")
changeCountryName(["St. Vincent and the Grenadines"], "Saint Vincent and the Grenadines")
changeCountryName(["Lao People's Democratic Republic", "Lao PDR"], "Laos")
changeCountryName(["Republic of Korea", "Korea, Rep.", "South Korea"], "South Korea")
changeCountryName(["Micronesia (Fed. States of)", "Micronesia, Fed. Sts."], "Micronesia (country)")
changeCountryName(["Ethiopia (excludes Eritrea)"], "Ethiopia")
changeCountryName(["United Republic of Tanzania"], "Tanzania")
changeCountryName(["Iran (Islamic Republic of)", "Iran, Islamic Rep."], "Iran")
changeCountryName(["St. Kitts and Nevis"], "Saint Kitts and Nevis")
changeCountryName(["Syrian Arab Republic"], "Syria")
changeCountryName(["Republic of Moldova"], "Moldova")
changeCountryName(["Russian Federation"], "Russia")
changeCountryName(["Brunei Darussalam"], "Brunei")
changeCountryName(["Egypt, Arab Rep."], "Egypt")
changeCountryName(["Kyrgyz Republic"], "Kyrgyzstan")
changeCountryName(["Macedonia, FYR"], "North Macedonia")
changeCountryName(["Slovak Republic"], "Slovakia")
changeCountryName(["Czech Republic"], "Czechia")
changeCountryName(["CÃ´te d'Ivoire"], "Cote d'Ivoire")
changeCountryName(["United States of America"], "United States")
changeCountryName(["Bahamas, The"], "Bahamas")
changeCountryName(["Gambia, The"], "Gambia")
changeCountryName(["Yemen, Rep."], "Yemen")
changeCountryName(["Timor-Leste"], "East Timor")
changeCountryName(["Cabo Verde"], "Cape Verde")
changeCountryName(["St. Lucia"], "Saint Lucia")
changeCountryName(['Swaziland'],'Eswatini')
changeCountryName(["TÃ¼rkiye", "Turkiye"], "Turkey")

In [1065]:
country_bmi = set(bmi.Country.unique())
country_gdp = set(gdp_per_capita.Country.unique())
country_life = set(life_expectancy.Country.unique())
country_male = set(male_ratio.Country.unique())
country_old = set(old_ratio.Country.unique())
country_young = set(young_ratio.Country.unique())
country_population = set(population.Country.unique())
country_urban = set(urban_population_ratio.Country.unique())
country_area = set(area.Country.unique())
country_infant = set(infant_mortality["Country or Area"].unique())
country_sdg = set(sdg_regions['Country/area'].unique())

In [1066]:
common_countries = country_bmi.intersection(country_bmi,country_gdp, country_life, country_male, 
                                             country_old, country_young, 
                                             country_population, country_urban, 
                                             country_area, country_infant, 
                                             country_sdg)

print("Common Countries across all datasets:")
print(common_countries)
print(len(common_countries))

Common Countries across all datasets:
{'Ecuador', 'Central African Republic', 'South Africa', 'Iceland', 'Lithuania', 'Democratic Republic of the Congo', 'Iran', 'Vietnam', 'Kyrgyzstan', 'Pakistan', 'Uganda', 'Italy', 'Colombia', 'Comoros', 'Sierra Leone', 'Liberia', 'Sudan', 'Guinea', 'Solomon Islands', 'Sweden', 'Austria', 'Papua New Guinea', 'Ukraine', 'Angola', 'Brunei', 'Burundi', "Cote d'Ivoire", 'Tuvalu', 'Dominican Republic', 'Turkmenistan', 'Niger', 'Tunisia', 'Yemen', 'Bulgaria', 'Uzbekistan', 'Afghanistan', 'Finland', 'Guyana', 'Nepal', 'Bosnia and Herzegovina', 'Myanmar', 'Rwanda', 'Eswatini', 'Iraq', 'Luxembourg', 'Vanuatu', 'Sao Tome and Principe', 'Cape Verde', 'Croatia', 'Netherlands', 'Zimbabwe', 'Somalia', 'Georgia', 'Russia', 'Montenegro', 'Cameroon', 'Albania', 'Cyprus', 'Lebanon', 'Philippines', 'Barbados', 'Tonga', 'Qatar', 'Mauritius', 'Germany', 'Mexico', 'Switzerland', 'Antigua and Barbuda', 'Hungary', 'Argentina', 'Paraguay', 'Thailand', 'Libya', 'Morocco', 'Nigeria', 'Australia', 'Denmark', 'Kuwait', 'Saudi Arabia', 'Canada', 'India', 'Guatemala', 'Panama', 'Greece', 'Costa Rica', 'Poland', 'Kazakhstan', 'Slovenia', 'Micronesia (country)', 'Kiribati', 'Senegal', 'Mauritania', 'Spain', 'United Kingdom', 'Algeria', 'Nicaragua', 'Tanzania', 'Guinea-Bissau', 'Chile', 'Marshall Islands', 'Bolivia', 'South Korea', 'Syria', 'Congo', 'Malaysia', 'Madagascar', 'Romania', 'Bhutan', 'Palau', 'Honduras', 'Suriname', 'Saint Lucia', 'Turkey', 'Malawi', 'Indonesia', 'Belize', 'Ethiopia', 'Azerbaijan', 'Oman', 'Sri Lanka', 'Haiti', 'Maldives', 'France', 'Venezuela', 'Belgium', 'Zambia', 'China', 'Portugal', 'Ghana', 'Bangladesh', 'Slovakia', 'Brazil', 'East Timor', 'Eritrea', 'Laos', 'Cuba', 'Jordan', 'Israel', 'Armenia', 'Ireland', 'Fiji', 'Equatorial Guinea', 'Mozambique', 'Benin', 'Singapore', 'Malta', 'Nauru', 'Samoa', 'Saint Vincent and the Grenadines', 'Japan', 'Namibia', 'Dominica', 'Egypt', 'Lesotho', 'Gambia', 'Latvia', 'Saint Kitts and Nevis', 'Mali', 'Mongolia', 'North Macedonia', 'Seychelles', 'Cambodia', 'Jamaica', 'Bahrain', 'Bahamas', 'Grenada', 'Belarus', 'Botswana', 'Chad', 'Norway', 'Tajikistan', 'United States', 'Czechia', 'Kenya', 'Peru', 'Estonia', 'Moldova', 'New Zealand', 'Togo', 'Uruguay', 'Burkina Faso', 'Gabon', 'Serbia', 'Djibouti', 'El Salvador', 'United Arab Emirates', 'Trinidad and Tobago'}
187

In [1067]:
all_countries = (country_bmi | country_gdp | country_life | country_male | 
                 country_old | country_young | country_population | 
                 country_urban | country_area | country_infant | 
                 country_sdg)
non_common_countries = all_countries - common_countries

print("Countries not in common across all datasets:")
print(non_common_countries)

Countries not in common across all datasets:
{'WB region: Middle East and North Africa (excluding high income)', 'Less developed regions, excluding China', 'Bouvet Island', 'WB region: Sub-Saharan Africa (excluding high income)', 'Group A â€“ already peaked (before 2024)', 'IPCC AR6: North America', 'CuraÃ§ao', 'European Union (EU: 27)', 'ECA: Oil LDCs', 'IDA total', 'Bolivarian Alliance for the Americas (ALBA)', 'Polynesia', 'Group C: Northern Africa and Western Asia', 'ECA: ECOWAS', 'IDA only', 'LLDC: Latin America', 'Channel Islands', 'Group B: Oceania (excluding Australia and New Zealand)', 'Other', 'WHO: South-East Asia region (SEARO)', 'Aruba', 'Group of Seven (G7)', 'ECA: Small Island states', 'ECA: CEN-SAD', 'UNFPA Regions', 'Greenland', 'Post-demographic dividend', 'Guam', 'United Nations Member States', 'Saint Pierre and Miquelon', 'ECA: North Africa', 'ECE: Euro area (EMU)', 'ESCWA: Countries in conflict', 'ESCAP: WB High Income Economies', 'Belt-Road Initiative: Latin America and the Caribbean', 'ECA: Island economies', 'Anguilla', 'More developed regions', 'Least developed: Latin America and the Caribbean', 'WHO: African region (AFRO)', 'Group B: Eastern and South-Eastern Asia', 'Group C: Sub-Saharan Africa', 'ECE: West Balkans (ST7)', 'Cook Islands', 'Northern America', 'UNICEF Regions: West and Central Africa', 'Gulf Cooperation Council (GCC)', 'Land-locked Countries', 'Commonwealth: Africa', 'East Asia & Pacific (IDA & IBRD countries)', 'Group B: Latin America and the Caribbean', 'Europe & Central Asia', 'Countries with Access to the Sea: Africa', 'Mayotte', 'Other small states', 'UNFPA: East and Southern Africa (ESA)', 'European Free Trade Agreement (EFTA)', 'Caribbean', 'IPCC AR6: Eastern Asia', 'United States Virgin Islands', 'Latin American and Caribbean Group (GRULAC)', 'Central Europe and the Baltics', 'China, Macao SAR', 'Least developed: Asia', 'Bermuda', 'Reunion', 'East Asia & Pacific', 'Kosovo (under UNSC res. 1244)', 'ESCWA: Non-conflict middle income countries', 'Small states', 'Low income', 'IDA blend', 'Group B: Sub-Saharan Africa', 'ESCAP: SAARC (SAARC)', 'Economic Community of West African States (ECOWAS)', 'UNFPA: Arab States (AS)', 'ECA: EAC', 'ECA: Eastern Africa', 'WHO: European Region (EURO)', 'ESCAP: LDC (LDC_E)', 'Least developed: Oceania', 'ESCAP: South and South-West Asia (SSWA)', 'Middle Africa', 'ADB region: Central and West Asia', 'Virgin Islands (U.S.)', 'Upper middle income', 'Middle-income countries', 'Central and Southern Asia', 'ESCAP: WB Low Income Economies', 'South Georgia and the South Sandwich Islands', 'WB region: East Asia and Pacific (excluding high income)', 'WHO: Western Pacific region (WPRO)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'BRICS', 'LLDC: Africa', 'Eastern European Group', 'ECE: CIS (CWG)', 'IDA & IBRD total', 'East Asia & Pacific (excluding high income)', 'Africa Eastern and Southern', 'UNICEF Regions: East Asia and Pacific', 'Guernsey', 'African Union: Western Africa', 'African Union: Northern Africa', 'Countries with Access to the Sea: Latin America and the Caribbean', 'ECA: Non-Oil Producing', 'Countries with Access to the Sea: Europe', 'ESCAP: Pacific island developing economies (PIDE)', 'Middle East & North Africa (excluding high income)', 'UNICEF Regions: Middle East and North Africa', 'Belt-Road Initiative: Africa', 'France (and dependencies)', 'New EU member states (joined since 2004)', 'UNICEF PROGRAMME REGIONS', 'Macao', 'Group A: Oceania (excluding Australia and New Zealand)', 'Group C: Central and Southern Asia', 'WHO: Americas (AMRO)', 'Five EyesÂ (FVEY)', 'Andorra', 'Wallis and Futuna', 'French Guiana', 'UNICEF Regions: Eastern and Southern Africa', 'IBRD only', 'Bonaire, Sint Eustatius and Saba', 'UNICEF Regions: Europe and Central Asia', 'Saint Martin (French part)', 'European Union (EU: 15)', 'Middle income', 'Other non-specified areas', 'Group B: Northern Africa and Western Asia', 'LLDC: Asia', 'African Union', 'Less developed: Africa', 'ESCAP: ADB Developing member countries (ADB_DMC)', 'Eastern Europe', 'Pacific island small states', 'Western European and Others Group (WEOG)', 'Heavily indebted poor countries (HIPC)', 'UNICEF Programme Regions: South Asia (ROSA)', 'Southern Asia', 'Europe', 'ESCAP: Europe (Europe)', 'Group A: Northern Africa and Western Asia', 'IPCC AR6: Eastern Europe and West-Central Asia', 'ESCAP: Africa (AFR)', 'Wallis and Futuna Islands', 'Hong Kong', 'Christmas Island', 'Group of Eight (G8)', 'UNICEF Regions: Sub-Saharan Africa', 'United States Minor Outlying Islands', 'Palestine', 'ESCAP: ADB Group A (ADB_DMC_A)', 'Group C: Latin America and the Caribbean', 'AUKUS', 'World Bank Regional Groups (developing only)', 'Organization of American States (OAS)', 'More developed: Asia', 'Hong Kong SAR, China', 'WHO Regions', 'Late-demographic dividend', 'UNICEF Programme Regions: Latin America', 'New Zealand (and dependencies)', 'Commonwealth of Nations', 'American Samoa', 'Belt-Road Initiative (BRI)', 'Lancang-Mekong Cooperation (LMC)', 'French Polynesia', 'Lower-middle-income countries', 'ESCAP: Other Area (OTH_REGION)', 'Korea, Dem. Rep.', 'Oceania', 'Caribbean small states', 'Asia-Pacific Economic Cooperation (APEC)', 'Least developed countries', 'Eastern Asia', 'French Southern Territories', 'UNICEF Regions: Western Europe', 'Latin America & Caribbean', 'West Bank and Gaza', 'Southern African Development Community (SADC)', 'Europe, Northern America, Australia, and New Zealand', 'UNICEF Programme Regions: West and Central Africa (WCARO)', 'Least developed countries: UN classification', 'Less developed regions', 'Commonwealth: Europe', 'Group A: Eastern and South-Eastern Asia', 'Commonwealth: Pacific', 'Least developed: Africa', 'ECA: African Union Commission', 'Holy See', 'UNFPA: Eastern Europe and Central Asia (EECA)', 'ESCWA: Arab Low-Income Countries (LICs)', 'South America', 'ECA: COMESA', 'IPCC AR6: Africa', 'UNICEF Regions: Eastern Europe and Central Asia', 'ESCWA: Arab countries', 'Vatican', 'More developed: Europe', 'Asia-Pacific Group', 'ESCAP: LLDC (LLDC_E)', 'CANZUK', 'WB region: Europe and Central Asia (excluding high income)', 'Northern Africa and Western Asia', 'British Indian Ocean Territory', 'Economic Cooperation Organization (ECO)', 'Falkland Islands', 'Cocos Islands', 'Organization for Security and Co-operation in Europe (OSCE)', 'African, Caribbean and Pacific (ACP) Group of States', 'South Asia (IDA & IBRD)', 'Group of 77 (G77)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Low-and-middle-income countries', 'ECE: United Nations Economic Commission for Europe - All countries', 'ESCAP: North and Central Asia (NCA)', 'Lower middle income', 'African Union: Eastern Africa', 'ADB region: Southeast Asia', 'Belt-Road Initiative: Asia', 'ECA: Oil producing economies', 'Group B: Europe, Northern America, Australia and New Zealand', 'UNFPA: Asia and the Pacific (AP)', 'Europe & Central Asia (excluding high income)', 'ESCWA: Maghreb subregion', 'ESCAP: WB Upper Middle Income Economies', 'Euro area', 'ESCAP: South-East Asia (SEA)', 'Less developed: Asia', 'Commonwealth: Asia', 'Denmark (and dependencies)', 'New Caledonia', 'Countries with Access to the Sea: Northern America', 'ECA: Land-locked countries', 'Melanesia', 'RÃ©union', 'Niue', 'Western Europe', 'SIDS Caribbean', 'Saint Helena', 'High-and-upper-middle-income countries', 'UNICEF Programme Regions: Eastern Caribbean', 'UNICEF Programme Regions: Latin America and Caribbean (LACRO)', 'UNICEF Programme Regions: Eastern and Southern Africa (ESARO)', 'Group of Twenty (G20) - member states', 'Norfolk Island', 'South-Eastern Asia', 'ECA: Mineral-rich countries', 'Group C: Europe, Northern America, Australia and New Zealand', 'IPCC AR6: South-East Asia and Pacific', 'UNFPA: Latin America and the Caribbean (LAC)', 'Heard Island and McDonald Islands', 'Group B â€“ peaking (between 2025-2054)', 'Macao SAR, China', 'Tokelau', 'UNICEF Programme Regions: East Asia and Pacific (EAPRO)', 'Eurasian Economic Community (Eurasec)', 'ESCWA: Mashreq subregion', 'Sint Maarten (Dutch part)', 'St. Martin (French part)', 'Fragile and conflict affected situations', 'Curacao', 'ESCAP: PACIFIC (PAC)', 'ESCAP: United Nations Economic and Social Commission for Asia and the Pacific - All countries', "Korea, Dem. People's Rep.", 'Cayman Islands', 'Latin American Integration Association (ALADI)', 'North America', 'Organization of Petroleum Exporting countries (OPEC)', 'Central Asia', 'ECLAC: Latin America', 'Latin America and the Caribbean', 'Black Sea Economic Cooperation (BSEC)', 'African Union: Central Africa', 'ECA: AMU', 'Australia/New Zealand', 'Small Island Developing States (SIDS)', 'China, Hong Kong SAR', 'Organisation for Economic Co-operation and Development (OECD)', 'Aland Islands', 'League of Arab States (LAS, informal name: Arab League)', 'ECE: Eastern Europe, Caucasus and Central Asia (CIS)', 'ADB region: East Asia', 'Africa Western and Central', 'WB region: Latin America and Caribbean (excluding high income)', 'Faroe Islands', 'Gibraltar', 'Africa', 'Isle of Man', 'More developed: Oceania', 'South Sudan', 'ESCAP: ADB Group C (ADB_DMC_C)', 'Caribbean Community and Common Market (CARICOM)', 'Less developed: Latin America and the Caribbean', 'Europe (48)', 'Sub-Saharan Africa (excluding high income)', 'Europe and Northern America', 'Group A: Sub-Saharan Africa', 'Europe & Central Asia (IDA & IBRD countries)', 'LLDC: Europe', 'Pre-demographic dividend', 'Turks and Caicos Islands', 'IPCC AR6: Southern Asia', 'North Atlantic Treaty Organization (NATO)', 'ADB region: Developed', 'North Korea', 'High-income countries', 'Less developed: Oceania', 'ECA: Central Africa', 'Non-Self-Governing Territories', 'Northern Europe', 'World', 'Group A: Europe, Northern America, Australia and New Zealand', 'UNICEF REGIONS', 'No income group available', 'ECA: West Africa', 'European Union (EU: 28)', 'Southern Africa', 'Montserrat', 'UNICEF Regions: South Asia', 'ADB region: The Pacific', 'Group C â€“ growing (peak after 2055)', 'ECA: Sahel', 'Saint BarthÃ©lemy', 'BRIC', 'Middle East & North Africa (IDA & IBRD countries)', 'State of Palestine', 'Kosovo', 'Indo-Pacific Economic Framework (IPEF)', 'Commonwealth of Independent States (CIS)', 'South Asian Association for Regional Cooperation (SAARC)', 'Asia', 'United States-Mexico-Canada Agreement (USMCA)', 'Belt-Road Initiative: Pacific', 'WB region: South Asia (excluding high income)', 'ESCAP: ADB Group B (ADB_DMC_B)', 'Saint Barthelemy', 'More developed: Northern America', 'ECA: Non-Oil LDCs', 'European Community (EC: 12)', 'Greater Arab Free Trade Area (GAFTA)', 'Central European Free Trade Agreement (CEFTA)', 'Bonaire Sint Eustatius and Saba', 'Group C: Eastern and South-Eastern Asia', 'Western Africa', 'ECLAC: United Nations Economic Commission for Latin America and the Caribbean - All countries', 'Arab World', 'African Union: Southern Africa', 'ESCAP: WB Lower Middle Income Economies', "Dem. People's Republic of Korea", 'ESCAP: ASEAN (ASEAN)', 'OECD members', 'ECA: Least developed countries', 'SIDS Pacific', 'Land-locked Developing Countries (LLDC)', 'UNICEF Programme Regions: Europe and Central Asia (CEECIS)', 'Countries with Access to the Sea: Asia', 'African Group', 'European Union', 'ADB region: South Asia', 'Sub-Saharan Africa', 'Upper-middle-income countries', 'Central America', 'Countries with Access to the Sea', 'Southern Europe', 'Western Sahara', 'ESCAP: ENEA including Russian Fed (ENEA_RUS)', 'Andean Community', 'ECA: Southern Africa', 'Group B: Central and Southern Asia', 'High income', 'ESCWA: Arab LDCs subregion', 'IPCC AR6: Europe', 'Martinique', 'UNICEF Regions: Latin America and Caribbean', 'United States of America (and dependencies)', 'Jersey', 'Micronesia', 'Puerto Rico', 'WHO: Eastern Mediterranean Region (EMRO)', 'IPCC AR6: Australia, Japan, and New Zealand', 'China (and dependencies)', 'Eastern and South-Eastern Asia', 'Land-locked Countries (Others)', 'Low-and-Lower-middle-income countries', 'United Kingdom (and dependencies)', 'ECA: IGAD', 'Commonwealth: Caribbean and Americas', 'San Marino', 'Northern Mariana Islands', 'ECA: United Nations Economic Commission for Africa - All countries', 'Falkland Islands (Malvinas)', 'Countries with Access to the Sea: Oceania', 'ECLAC: Caribbean', 'Oceania (excluding Australia and New Zealand)', 'Eastern Africa', 'ECE: European Union (E25)', 'ESCAP: ECO (ECO)', 'Group C: Oceania (excluding Australia and New Zealand)', 'ECA: ECCAS', 'UNFPA: West and Central Africa (WCA)', 'Svalbard and Jan Mayen', 'ESCWA: Gulf Cooperation Council (GCC)', 'ESCAP: North America (NAM)', 'British Virgin Islands', 'East African Community (EAC)', 'Group A: Latin America and the Caribbean', 'South Asia', 'Southern Common Market (MERCOSUR)', 'Organization of Islamic Cooperation (OIC)', 'Low-income countries', 'IPCC AR6: Latin America and Caribbean', 'ESCAP: Countries with Special Needs', 'Early-demographic dividend', 'Latin America & Caribbean (excluding high income)', 'ESCAP: East and North-East Asia (ENEA)', 'SIDS Atlantic, Indian Ocean and South China Sea (AIS)', 'Association of Southeast Asian Nations (ASEAN)', 'West African Economic and Monetary Union (UEMOA)', 'Middle East & North Africa', 'Western Asia', 'Monaco', 'UNICEF Programme Regions: Middle East and North Africa (MENARO)', 'Low & middle income', 'Economic Community of Central African States (ECCAS)', 'Netherlands (and dependencies)', 'Pitcairn', 'ECA: Land-locked LDCs', 'Northern Africa', 'Liechtenstein', 'Quadrilateral Security Dialogue (QSD) (colloquially the Quad)', 'Americas', 'UNICEF Regions: North America', 'ESCWA: Arab Middle-Income Countries (MICs)', 'ECA: Sub-Saharan Africa', 'ESCAP: Small Islands Developing States', 'Belt-Road Initiative: Europe', 'ESCAP: Latin America (LAC)', 'Guadeloupe', 'Less developed regions, excluding least developed countries', 'ECA: SADC', 'Shanghai Cooperation Organization (SCO)', 'IPCC AR6: Middle East'}

In [1068]:
with open("not_needed.txt", "r",encoding="UTF-8") as file:
    not_needed = {line.strip() for line in file}
bad_countries = [i for i in non_common_countries if i not in not_needed]
bad_countries = sorted(bad_countries, key=lambda x: -len(x))
print(len(bad_countries))
for i in bad_countries[:8]:
    print(i)

0

In [1069]:
m1 = pd.merge(young_ratio, old_ratio, on=["Country","Year"], how='inner')
m2 = pd.merge(m1, sdg_regions, left_on=["Country"], right_on=["Country/area"], how='inner')
m2.drop(columns="Country/area",inplace=True)
m2.rename(columns={'2024': 'SDG Region'}, inplace=True)
m3 = pd.merge(m2, population, on=["Country","Year"], how='inner')
m4 = pd.merge(m3, male_ratio, on=["Country","Year"], how='inner')
m5 = pd.merge(m4, urban_population_ratio, on=["Country","Year"], how='inner')
m6 = pd.merge(m5, area, on=["Country","Year"], how='inner')
m7 = pd.merge(m6, gdp_per_capita, on=["Country","Year"], how='inner')
m8 = pd.merge(m7, life_expectancy, on=["Country","Year"], how='inner')
m9 = pd.merge(m8, infant_mortality, left_on=["Country","Year"], right_on=["Country or Area","Year(s)"], how='inner')
m9.drop(columns=["Country or Area","Year(s)"],inplace=True)
m10 = pd.merge(m9, bmi, on=["Country","Year"], how='inner')
m10

,Country,Year,Young Age Dependency Ratio,Retirement Age Dependency Ratio,SDG Region,Population,Male Population Ratio,Urban Population Ratio,Total Area (sq km),GDP_per_Capita,Life Expectancy,Infant mortality per 1000 live births,BMI,BMI Female,BMI Male
0,Afghanistan,2016,87.405774,4.606351,Central and Southern Asia,34636207,50.585392,25.020,652860.0,523.053012,63.136,54.4866,23.4,24.1,22.6
1,Afghanistan,2015,88.398202,4.644246,Central and Southern Asia,33753499,50.576819,24.803,652860.0,566.881130,62.659,56.1285,23.3,24.0,22.5
2,Afghanistan,2014,90.015900,4.690797,Central and Southern Asia,32716210,50.567865,24.587,652860.0,626.512929,62.545,57.4750,23.2,23.9,22.4
3,Afghanistan,2013,92.388046,4.737487,Central and Southern Asia,31541209,50.557897,24.373,652860.0,638.733181,62.417,58.7879,23.0,23.7,22.3
4,Afghanistan,2012,94.533123,4.767237,Central and Southern Asia,30466479,50.544420,24.160,652860.0,653.417475,61.923,60.7803,22.9,23.6,22.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7122,Zimbabwe,1979,108.320784,7.461233,Sub-Saharan Africa,6655833,46.870076,21.853,390760.0,777.883009,55.038,69.8009,22.3,24.0,20.5
7123,Zimbabwe,1978,105.613450,7.032998,Sub-Saharan Africa,6549349,47.536053,21.345,390760.0,664.432526,54.593,70.5353,22.2,23.9,20.4
7124,Zimbabwe,1977,103.098512,6.695480,Sub-Saharan Africa,6453044,48.270599,20.846,390760.0,676.329202,56.285,71.0838,22.1,23.9,20.3
7125,Zimbabwe,1976,101.949515,6.566900,Sub-Saharan Africa,6288387,48.593463,20.356,390760.0,686.721730,56.936,71.3479,22.1,23.8,20.2
7126,Zimbabwe,1975,101.330144,6.517293,Sub-Saharan Africa,6097083,48.736732,19.873,390760.0,716.949515,57.552,71.4789,22.0,23.8,20.1

In [1071]:

from itertools import combinations
def check_unique_column_pairs(df):
    unique_pairs = {}
    for col1, col2 in combinations(df.columns, 2):
        is_unique = df.duplicated(subset=[col1, col2]).sum() == 0
        unique_pairs[(col1, col2)] = is_unique
    return unique_pairs

unique_pairs_result = check_unique_column_pairs(m10)

for pair, is_unique in unique_pairs_result.items():
    print(f"Columns {pair} are unique: {is_unique}")

Columns ('Country', 'Year') are unique: True
Columns ('Country', 'Young Age Dependency Ratio') are unique: True
Columns ('Country', 'Retirement Age Dependency Ratio') are unique: True
Columns ('Country', 'SDG Region') are unique: False
Columns ('Country', 'Population') are unique: False
Columns ('Country', 'Male Population Ratio') are unique: True
Columns ('Country', 'Urban Population Ratio') are unique: False
Columns ('Country', 'Total Area (sq km)') are unique: False
Columns ('Country', 'GDP_per_Capita') are unique: True
Columns ('Country', 'Life Expectancy') are unique: False
Columns ('Country', 'Infant mortality per 1000 live births') are unique: False
Columns ('Country', 'BMI') are unique: False
Columns ('Country', 'BMI Female') are unique: False
Columns ('Country', 'BMI Male') are unique: False
Columns ('Year', 'Young Age Dependency Ratio') are unique: True
Columns ('Year', 'Retirement Age Dependency Ratio') are unique: True
Columns ('Year', 'SDG Region') are unique: False
Columns ('Year', 'Population') are unique: True
Columns ('Year', 'Male Population Ratio') are unique: True
Columns ('Year', 'Urban Population Ratio') are unique: False
Columns ('Year', 'Total Area (sq km)') are unique: False
Columns ('Year', 'GDP_per_Capita') are unique: True
Columns ('Year', 'Life Expectancy') are unique: False
Columns ('Year', 'Infant mortality per 1000 live births') are unique: True
Columns ('Year', 'BMI') are unique: False
Columns ('Year', 'BMI Female') are unique: False
Columns ('Year', 'BMI Male') are unique: False
Columns ('Young Age Dependency Ratio', 'Retirement Age Dependency Ratio') are unique: True
Columns ('Young Age Dependency Ratio', 'SDG Region') are unique: True
Columns ('Young Age Dependency Ratio', 'Population') are unique: True
Columns ('Young Age Dependency Ratio', 'Male Population Ratio') are unique: True
Columns ('Young Age Dependency Ratio', 'Urban Population Ratio') are unique: True
Columns ('Young Age Dependency Ratio', 'Total Area (sq km)') are unique: True
Columns ('Young Age Dependency Ratio', 'GDP_per_Capita') are unique: True
Columns ('Young Age Dependency Ratio', 'Life Expectancy') are unique: True
Columns ('Young Age Dependency Ratio', 'Infant mortality per 1000 live births') are unique: True
Columns ('Young Age Dependency Ratio', 'BMI') are unique: True
Columns ('Young Age Dependency Ratio', 'BMI Female') are unique: True
Columns ('Young Age Dependency Ratio', 'BMI Male') are unique: True
Columns ('Retirement Age Dependency Ratio', 'SDG Region') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Population') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Male Population Ratio') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Urban Population Ratio') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Total Area (sq km)') are unique: True
Columns ('Retirement Age Dependency Ratio', 'GDP_per_Capita') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Life Expectancy') are unique: True
Columns ('Retirement Age Dependency Ratio', 'Infant mortality per 1000 live births') are unique: True
Columns ('Retirement Age Dependency Ratio', 'BMI') are unique: True
Columns ('Retirement Age Dependency Ratio', 'BMI Female') are unique: True
Columns ('Retirement Age Dependency Ratio', 'BMI Male') are unique: True
Columns ('SDG Region', 'Population') are unique: False
Columns ('SDG Region', 'Male Population Ratio') are unique: True
Columns ('SDG Region', 'Urban Population Ratio') are unique: False
Columns ('SDG Region', 'Total Area (sq km)') are unique: False
Columns ('SDG Region', 'GDP_per_Capita') are unique: True
Columns ('SDG Region', 'Life Expectancy') are unique: False
Columns ('SDG Region', 'Infant mortality per 1000 live births') are unique: False
Columns ('SDG Region', 'BMI') are unique: False
Columns ('SDG Region', 'BMI Female') are unique: False
Columns ('SDG Region', 'BMI Male') are unique: False
Columns ('Population', 'Male Population Ratio') are unique: True
Columns ('Population', 'Urban Population Ratio') are unique: False
Columns ('Population', 'Total Area (sq km)') are unique: False
Columns ('Population', 'GDP_per_Capita') are unique: True
Columns ('Population', 'Life Expectancy') are unique: True
Columns ('Population', 'Infant mortality per 1000 live births') are unique: True
Columns ('Population', 'BMI') are unique: True
Columns ('Population', 'BMI Female') are unique: True
Columns ('Population', 'BMI Male') are unique: True
Columns ('Male Population Ratio', 'Urban Population Ratio') are unique: True
Columns ('Male Population Ratio', 'Total Area (sq km)') are unique: True
Columns ('Male Population Ratio', 'GDP_per_Capita') are unique: True
Columns ('Male Population Ratio', 'Life Expectancy') are unique: True
Columns ('Male Population Ratio', 'Infant mortality per 1000 live births') are unique: True
Columns ('Male Population Ratio', 'BMI') are unique: True
Columns ('Male Population Ratio', 'BMI Female') are unique: True
Columns ('Male Population Ratio', 'BMI Male') are unique: True
Columns ('Urban Population Ratio', 'Total Area (sq km)') are unique: False
Columns ('Urban Population Ratio', 'GDP_per_Capita') are unique: True
Columns ('Urban Population Ratio', 'Life Expectancy') are unique: False
Columns ('Urban Population Ratio', 'Infant mortality per 1000 live births') are unique: True
Columns ('Urban Population Ratio', 'BMI') are unique: False
Columns ('Urban Population Ratio', 'BMI Female') are unique: False
Columns ('Urban Population Ratio', 'BMI Male') are unique: False
Columns ('Total Area (sq km)', 'GDP_per_Capita') are unique: True
Columns ('Total Area (sq km)', 'Life Expectancy') are unique: False
Columns ('Total Area (sq km)', 'Infant mortality per 1000 live births') are unique: False
Columns ('Total Area (sq km)', 'BMI') are unique: False
Columns ('Total Area (sq km)', 'BMI Female') are unique: False
Columns ('Total Area (sq km)', 'BMI Male') are unique: False
Columns ('GDP_per_Capita', 'Life Expectancy') are unique: True
Columns ('GDP_per_Capita', 'Infant mortality per 1000 live births') are unique: True
Columns ('GDP_per_Capita', 'BMI') are unique: True
Columns ('GDP_per_Capita', 'BMI Female') are unique: True
Columns ('GDP_per_Capita', 'BMI Male') are unique: True
Columns ('Life Expectancy', 'Infant mortality per 1000 live births') are unique: True
Columns ('Life Expectancy', 'BMI') are unique: False
Columns ('Life Expectancy', 'BMI Female') are unique: False
Columns ('Life Expectancy', 'BMI Male') are unique: False
Columns ('Infant mortality per 1000 live births', 'BMI') are unique: True
Columns ('Infant mortality per 1000 live births', 'BMI Female') are unique: False
Columns ('Infant mortality per 1000 live births', 'BMI Male') are unique: False
Columns ('BMI', 'BMI Female') are unique: False
Columns ('BMI', 'BMI Male') are unique: False
Columns ('BMI Female', 'BMI Male') are unique: False

In [1073]:
m10.sort_values(by=['Country', 'Year'], ascending=[True, False],inplace=True)
m10

,Country,Year,Young Age Dependency Ratio,Retirement Age Dependency Ratio,SDG Region,Population,Male Population Ratio,Urban Population Ratio,Total Area (sq km),GDP_per_Capita,Life Expectancy,Infant mortality per 1000 live births,BMI,BMI Female,BMI Male
0,Afghanistan,2016,87.405774,4.606351,Central and Southern Asia,34636207,50.585392,25.020,652860.0,523.053012,63.136,54.4866,23.4,24.1,22.6
1,Afghanistan,2015,88.398202,4.644246,Central and Southern Asia,33753499,50.576819,24.803,652860.0,566.881130,62.659,56.1285,23.3,24.0,22.5
2,Afghanistan,2014,90.015900,4.690797,Central and Southern Asia,32716210,50.567865,24.587,652860.0,626.512929,62.545,57.4750,23.2,23.9,22.4
3,Afghanistan,2013,92.388046,4.737487,Central and Southern Asia,31541209,50.557897,24.373,652860.0,638.733181,62.417,58.7879,23.0,23.7,22.3
4,Afghanistan,2012,94.533123,4.767237,Central and Southern Asia,30466479,50.544420,24.160,652860.0,653.417475,61.923,60.7803,22.9,23.6,22.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7122,Zimbabwe,1979,108.320784,7.461233,Sub-Saharan Africa,6655833,46.870076,21.853,390760.0,777.883009,55.038,69.8009,22.3,24.0,20.5
7123,Zimbabwe,1978,105.613450,7.032998,Sub-Saharan Africa,6549349,47.536053,21.345,390760.0,664.432526,54.593,70.5353,22.2,23.9,20.4
7124,Zimbabwe,1977,103.098512,6.695480,Sub-Saharan Africa,6453044,48.270599,20.846,390760.0,676.329202,56.285,71.0838,22.1,23.9,20.3
7125,Zimbabwe,1976,101.949515,6.566900,Sub-Saharan Africa,6288387,48.593463,20.356,390760.0,686.721730,56.936,71.3479,22.1,23.8,20.2
7126,Zimbabwe,1975,101.330144,6.517293,Sub-Saharan Africa,6097083,48.736732,19.873,390760.0,716.949515,57.552,71.4789,22.0,23.8,20.1

In [1074]:
m10.to_csv("cleaned_data.csv",index=False)